name: Zenthra Framework CI Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Cargo Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install System Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libx11-dev libx11-xcb-dev libxkbcommon-dev libwayland-dev libegl1-mesa-dev libgbm-dev
      - uses: dtolnay/rust-toolchain@stable
      - name: Run check
        run: cargo check
      - name: Run tests
        run: cargo test --workspace --exclude examples/window_test_mobile
